//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Info()
        {
            this.Progress = new HashSet<Progress>();
        }
    
        public int ProgressId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Langlevel { get; set; }
        public Nullable<int> TextCount { get; set; }
        public Nullable<int> RuleCount { get; set; }
        public Nullable<int> WordCount { get; set; }

        public Info(int userid, string langlevel, int textcount, int rulecount, int wordcount)
        {
            this.UserId = userid;
            this.Langlevel = langlevel;
            this.TextCount = textcount;
            this.RuleCount = rulecount;
            this.WordCount = wordcount;
        }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progress> Progress { get; set; }
    }
}
