//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ProgrId { get; set; }
        public Nullable<int> ProgressId { get; set; }
        public Nullable<int> TextId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public Nullable<bool> IsComplited { get; set; }
        //изменить
        public Progress()
        { 
        }
        public Progress(int progressid, ParametrType type, int parametrId, bool iscomplited)
        {
            this.ProgressId = progressid;
            switch (type)
            {
                case ParametrType.Text:
                    TextId = (int?)parametrId;
                    break;
                case ParametrType.Rule:
                    RuleId = (int?)parametrId;
                    break;
                default:
                    break;
            }
            this.IsComplited = iscomplited;
        }
        public virtual Info Info { get; set; }
        public virtual Rule Rule { get; set; }
        public virtual Text Text { get; set; }

        public enum ParametrType
        {
            Text,
            Rule
        }


    }
}
